# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Flows for APEX
logo: "/assets/images/logo.svg"
email:
description: >- # this means to ignore newlines until "baseurl:"
  All available resources for Flows for APEX in one place, designed to help you get started and learn more about the product.
minimal_mistakes_skin: default
search: true
search_full_content: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

collections:
  development:
    output: true
    permalink: /:collection/:path/
    type: "documentation"
    display_name: "Development"
    publish_date: 2021-10-20T00:00:00+00:00
    home_page: getting-started/
  latest:
    output: true
    permalink: /:collection/:path/
    type: "documentation"
    display_name: "Latest v21.1"
    publish_date: 2021-10-13T00:00:00+00:00
    home_page: getting-started/
  v5.1.2:
    output: true
    permalink: /:collection/:path/
    type: "documentation"
    display_name: "v5.1.2"
    publish_date: 2021-09-13T00:00:00+00:00
    home_page: tutorials/

defaults:
  # _development
  - scope:
      type: development
    values:
      classes: wide
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "development"
  # _latest
  - scope:
      type: latest
    values:
      classes: wide
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "latest"
  # _v5.1.2
  - scope:
      type: v5.1.2
    values:
      classes: wide
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "v5.1.2"
  # _posts
  - scope:
      path: "_posts"
      type: posts
      permalink: /:collection/:path/
    values:
      layout: single
      classes: wide
      show_date: true
      show_author: true
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
